[tool.pyright]
include = ["core", "cogs"]
exclude = [
  "**/__pycache__",
  ".git",
  ".ruff_cache",
  ".venv",
  ".vscode",
]
pythonVersion = "3.12"
typeCheckingMode = "basic"
reportUnusedImport = "error"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMissingParameterType = "error"
reportMissingTypeArgument = "error"
reportUnusedVariable = "warning"

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [
  ".git",
  ".ruff_cache",
  ".venv",
  ".vscode",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "UP",  # pyupgrade,
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "SIM", # flake8-simplify
  "TCH", # flake8-type-checking-hints
  "FA",  # flake8-future-annotations
]

[tool.ruff.lint.isort]
combine-as-imports = true